server:
  port: 8001


spring:
  application:
    name: service-cloud-payment
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.30.154.201:3306/test_one?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml